[env]
DATABASE_URL="postgresql://user:password@postgres:5432/db"
RUST_LOG="debug"

[config]
default_to_workspace = false

[tasks.backend-run]
command = "cargo"
args = ["run", "-p", "backend"]

[tasks.frontend-run]
command = "cargo"
args = ["run", "-p", "frontend"]

[tasks.db-migration]
command = "cargo"
args = ["sqlx", "migrate", "add", "${@}"]

[tasks.db-setup]
command = "sqlx"
args = ["database", "setup", "--source=./migrations/"]

[tasks.db-prepare]
command = "cargo"
args = ["sqlx", "prepare", "--", "-p", "backend"]
