[env]
RUST_LOG="debug"
DATABASE_URL="postgresql://user:password@postgres:5432/db"
BACKEND_URL="http://localhost:3000"
BACKEND_PORT=3000

[config]
default_to_workspace = false

[tasks.backend-run]
command = "cargo"
args = ["run", "-p", "backend"]

[tasks.frontend-run]
command = "trunk"
args = ["serve", "--address", "0.0.0.0", "--dist", "./target/dist", "./frontend/index.html"]

[tasks.db-migration]
command = "cargo"
args = ["sqlx", "migrate", "add", "${@}"]

[tasks.db-setup]
command = "sqlx"
args = ["database", "setup", "--source=./migrations/"]

[tasks.db-prepare]
command = "cargo"
args = ["sqlx", "prepare", "--", "-p", "backend"]
